[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"


[project]
name = "cryptocore"
version = "1.0.0"
description = "Command-line AES-128 ECB file encryption and decryption tool."
requires-python = ">=3.10"

dependencies = [
    "pycryptodome>=3.20.0"
]


[project.scripts]
cryptocore = "cryptocore.main:main"


[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]